import { Product } from "@/types";

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "nike-dunk-low-orange",
    name: "Nike Dunk Low Orange Blaze",
    description: "Zapatillas clásicas con diseño retro y colores vibrantes.",
    price: 120,
    category_slug: "Sneakers",
    featured: true,
    image: "/images/featured-products/nike-dunk-low-orange.png",
  },
  {
    id: "nike-pegasus-41",
    name: "Nike Pegasus 41",
    description:
      "Zapatillas de running con amortiguación reactiva y soporte para largas distancias.",
    price: 145,
    category_slug: "Sneakers",
    featured: true,
    image: "/images/featured-products/nike-pegasus-41.png",
  },
  {
    id: "nike-sportswear-hoodie",
    name: "Nike Sportswear Club Hoodie",
    description:
      "Sudadera con capucha de ajuste clásico y tejido suave. Ideal para el día a día.",
    price: 65,
    category_slug: "Ropa",
    featured: true,
    image: "/images/featured-products/nike-sportswear-hoodie.png",
  },
  {
    id: "nike-everyday-socks",
    name: "Nike Everyday Cushioned Socks",
    description:
      "Calcetines acolchados con soporte en el arco y tecnología Dri-FIT para mantenerte seco.",
    price: 28,
    category_slug: "Accesorios",
    featured: true,
    image: "/images/featured-products/nike-everyday-socks.png",
  },
  {
    id: "nike-crossbody-bag",
    name: "Nike Aura Crossbody Bag (2L)",
    description:
      "Bolso cruzado compacto y funcional con diseño moderno y resistente al agua.",
    price: 38,
    category_slug: "Accesorios",
    featured: true,
    image: "/images/featured-products/nike-crossbody-bag.png",
  },
  {
    id: "nike-dri-fit-tee",
    name: "Nike Dri-FIT Training T-Shirt",
    description:
      "Camiseta deportiva con tecnología Dri-FIT que absorbe el sudor y mantiene la frescura.",
    price: 30,
    category_slug: "Ropa",
    featured: true,
    image: "/images/featured-products/nike-dri-fit-tee.png",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "air-max-90-black-volt",
    name: "Nike Air Max 90",
    price: 149.99,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "Volt"],
    description:
      "Diseño clásico con amortiguación Air visible y detalles retro.",
    image: "/images/products/air-max-90-black-volt.webp",
    category_slug: "Apparel",
    type: "Sneakers",
    collection_slug: "Air Max",
    offer: false,
  },
  {
    id: "pegasus-41-mens",
    name: "Nike Pegasus 41",
    price: 764.95,
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["White", "Blue", "Crimson"],
    description:
      "Zapatillas de running con amortiguación ReactX para mayor retorno de energía.",
    image: "/images/products/pegasus-41-mens.webp",
    category_slug: "Running",
    type: "Sneakers",
    collection_slug: "Pegasus",
    offer: true,
    discount: 25,
  },
  {
    id: "dunk-low-retro",
    name: "Nike Dunk Low Retro",
    price: 794.95,
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["University Red", "White"],
    description: "Estilo clásico de skate con perfil bajo y colores icónicos.",
    image: "/images/products/dunk-low-retro.webp",
    category_slug: "Skateboarding",
    type: "Sneakers",
    collection_slug: "Dunk",
    offer: false,
  },
  {
    id: "air-force-1-kids",
    name: "Nike Air Force 1 (Niños)",
    price: 589.95,
    sizes: ["3Y", "4Y", "5Y", "6Y"],
    colors: ["White", "Black"],
    description:
      "Versión infantil del clásico Air Force 1 con durabilidad y estilo.",
    image: "/images/products/air-force-1-kids.webp",
    category_slug: "Kids",
    type: "Sneakers",
    collection_slug: "Air Max",
    offer: true,
    discount: 30,
  },
  {
    id: "winflo-11-mens",
    name: "Nike Winflo 11",
    price: 599.95,
    sizes: ["8", "9", "10", "11"],
    colors: ["Grey", "Volt"],
    description: "Zapatillas de running con soporte y tracción para pavimento.",
    image: "/images/products/winflo-11-mens.webp",
    category_slug: "Running",
    type: "Sneakers",
    collection_slug: "React",
    offer: false,
  },
  {
    id: "sb-dunk-low-pro",
    name: "Nike SB Dunk Low Pro",
    price: 794.95,
    sizes: ["7", "8", "9", "10"],
    colors: ["Black", "Gum"],
    description:
      "Zapatillas de skate con amortiguación Zoom Air y agarre superior.",
    image: "/images/products/sb-dunk-low-pro.webp",
    category_slug: "Skateboarding",
    type: "Sneakers",
    collection_slug: "SB",
    offer: true,
    discount: 20,
  },
  {
    id: "tech-woven-jacket",
    name: "Nike Tech Woven Jacket",
    price: 739.95,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Olive"],
    description:
      "Chaqueta ligera con tejido repelente al agua y diseño urbano.",
    image: "/images/products/tech-woven-jacket.webp",
    category_slug: "Apparel",
    type: "Ropa",
    collection_slug: "",
    offer: false,
  },
  {
    id: "sportswear-windrunner-kids",
    name: "Nike Sportswear Windrunner (Niños)",
    price: 334.95,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Grey"],
    description: "Chaqueta repelente con capucha y diseño clásico Windrunner.",
    image: "/images/products/sportswear-windrunner-kids.webp",
    category_slug: "Kids",
    type: "Ropa",
    collection_slug: "",
    offer: true,
    discount: 30,
  },
  {
    id: "swoosh-bra-girls",
    name: "Nike Swoosh Bra (Niña)",
    price: 144.95,
    sizes: ["XS", "S", "M"],
    colors: ["Pink", "Black"],
    description: "Bra deportivo con soporte medio y tecnología Dri-FIT.",
    image: "/images/products/swoosh-bra-girls.webp",
    category_slug: "Training",
    type: "Ropa",
    collection_slug: "",
    offer: false,
  },
  {
    id: "heritage-vulc-skate",
    name: "Nike SB Heritage Vulc",
    price: 429.95,
    sizes: ["7", "8", "9", "10"],
    colors: ["White", "Navy"],
    description: "Zapatillas de skate con estilo retro y suela vulcanizada.",
    image: "/images/products/heritage-vulc-skate.webp",
    category_slug: "Skateboarding",
    type: "Sneakers",
    collection_slug: "SB",
    offer: true,
    discount: 20,
  },
  {
    id: "merc-superfly-10-academy",
    name: "Nike Mercurial Superfly 10 Academy",
    price: 619.95,
    sizes: ["8", "9", "10", "11"],
    colors: ["Bright Crimson", "Black"],
    description: "Guayos de fútbol con corte alto y tracción multidireccional.",
    image: "/images/products/merc-superfly-10-academy.webp",
    category_slug: "Football",
    type: "Sneakers",
    collection_slug: "",
    offer: false,
  },
  {
    id: "court-legacy-kids",
    name: "Nike Court Legacy (Niños)",
    price: 299.95,
    sizes: ["3Y", "4Y", "5Y"],
    colors: ["White", "Green"],
    description: "Zapatillas clásicas con estilo court y comodidad para niños.",
    image: "/images/products/court-legacy-kids.webp",
    category_slug: "Kids",
    type: "Sneakers",
    collection_slug: "",
    offer: true,
    discount: 25,
  },
  {
    id: "sportswear-tee-men",
    name: "Nike Sportswear Tee (Hombre)",
    price: 224.95,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
    description: "Camiseta básica con logo Nike y ajuste cómodo.",
    image: "/images/products/sportswear-tee-men.webp",
    category_slug: "Training",
    type: "Ropa",
    collection_slug: "",
    offer: false,
  },
  {
    id: "gym-club-duffle",
    name: "Nike Gym Club Duffel",
    price: 229.95,
    sizes: [],
    colors: ["Black", "Rose"],
    description:
      "Maleta de entrenamiento con capacidad de 24L y diseño funcional.",
    image: "/images/products/gym-club-duffle.webp",
    category_slug: "Training",
    type: "Accesorios",
    collection_slug: "",
    offer: true,
    discount: 15,
  },
  {
    id: "fc-barcelona-home-jersey",
    name: "FC Barcelona 2025/26 Home Jersey",
    price: 474.95,
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Red"],
    description: "Camiseta oficial con tecnología Dri-FIT y escudo del club.",
    image: "/images/products/fc-barcelona-home-jersey.webp",
    category_slug: "Football",
    type: "Ropa",
    collection_slug: "",
    offer: false,
  },
  {
    id: "air-max-craze",
    name: "Nike Air Max Craze",
    price: 329.99,
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["White", "Purple"],
    description: "Estilo audaz con unidad Air Max y diseño futurista.",
    image: "/images/products/air-max-craze.webp",
    category_slug: "Apparel",
    type: "Sneakers",
    collection_slug: "Air Max",
    offer: true,
    discount: 20,
  },
];
